### ISSUE TITLE
Simplify NodeList conversion

### ISSUE THREAD

**Issue by edg2s** [mooeypoo/formurlator#4]
https://github.com/mooeypoo/formurlator/blob/4d4784cfd7c6501437b37fc1a593a9243abb05d6/src/fr.Element.js#L53-L57

`var myArray = Array.prototype.slice.call( nodeList )`

...or, given that you do a filter on the next line, just use Array.prototype.filter.call(...) and use that as your conversion step too.

**Comment by mooeypoo** [comment]
Oh! I think I got a bit confused when I read about NodeList; there were several places that recommended not going with an array conversion like this -- but reading it again, it seemed like there isn't really a good reason not to (it supports all modern browsers anyways, I'm not sure why some places advised against it)

This is great, I'll fix it up. Thanks!
